# -*- coding: utf-8 -*-
"""Ship_WithCrews.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qAQ7rIENAH_YZNCc8jI97an3a4BsE253
"""

import requests

#go to starship API
url = "https://swapi.dev/api/starships/"


#get json data
json_data = requests.get(url).json()

# use try catch block for any value error and 
# check if crew size is between 3 and 100
# and print ship name

for ship in json_data['results']:
  crew = ship['crew']
  #print(ship['crew'])
  try:
    if 3 <= int(crew) <= 100: print(ship['name'])
  except ValueError:
    pass